vich_uploader:
    db_driver: orm
    mappings:
        projetdev_image:
            uri_prefix: /uploads/images/projets
            upload_destination: '%kernel.project_dir%/public/uploads/images/projets'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer 